---
- name: Install Docker binaries
  include_role:
    name: common
    tasks_from: apt.yaml
  vars:
    binaries: "{{ docker_binaries }}"
    handler_list: "{{ docker_handler_list }}"
  tags:
    - docker
    - docker_apt
